version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-node-browsers
    steps:
      - checkout
      - run: "flake8 . --exclude=*/old/*"
  test:
    docker:
      - image: circleci/python:3.7-node-browsers
    steps:
      - checkout
      - run: "flake8 . --exclude=*/old/*"